<?php
/**
 * Plugin Name:       Toast Entertainment Quote Builder
 * Plugin URI:        https://brianlawrence.com
 * Description:       Plugin to allow for a custom quote builder for Toast Entertainment
 * Version:           0.0.1
 * Author:            Dillon Lara
 * Author URI:        https://dillonlara.me
 * Text Domain:       teqb
 * Domain Path:       /languages
 *
 * Generated by WordPress Plugin Generator v1.1.1 (wordpressplugingenerator.com)
 *
 */

// Prevent to access the file from outside of WordPress
if(!defined('ABSPATH')) {
	exit;
}
if(!function_exists('wp_get_current_user')) {
	include(ABSPATH . 'wp-includes/pluggable.php');
}

class teqb_Loader {
	public $config = [
		'name' => 'Toast Entertainment Quote Builder',
		'version' => '0.0.1',
		'textDomain' => 'teqb',
		'textDomainPath' => 'languages',
		'slug' => 'toast-entertainment-quote-builder',
		'prefix' => 'teqb',
		'prefixSeparator' => '_',
	];
	
	//
	public function __construct() {
		self::init();

		self::start();
	}

	/**
	 * Initialize the plugin
	 */
	private function init() {
	}

	
	/**
	 * Deactivates the plugin due to the missing requirements.
	 */
	public function deactivate() {
		if(current_user_can('activate_plugins') && is_plugin_active(plugin_basename(__FILE__))) {
			deactivate_plugins(plugin_basename(__FILE__));
	
			// Hide the default "Plugin activated" notice
			if(isset($_GET['activate'])) {
				unset($_GET['activate']);
			}
		}
	}

	/**
	 * Starting the plugin.
	 */
	public function start() {
		require_once plugin_dir_path(__FILE__) . 'classes/plugin.php';
		$plugin = new teqb_Plugin($this->config);

		register_activation_hook(__FILE__, [&$plugin, 'activate']);
		register_deactivation_hook(__FILE__, [&$plugin, 'deactivate']);
	}
}

$teqb = new teqb_Loader();
